"""Chande user model

Revision ID: 78b408e6cf1b
Revises: bee864adbc79
Create Date: 2023-09-30 09:53:56.690059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78b408e6cf1b'
down_revision = 'bee864adbc79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('init_volume', sa.Float(), nullable=True))
    op.execute('UPDATE "user" SET init_volume = 1000')
    op.alter_column('user', 'init_volume', nullable=False)
    op.add_column('user', sa.Column('executed_binance', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('executed_bybit', sa.Float(), nullable=True))
    op.drop_constraint('user_base_coin_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'test_api')
    op.drop_column('user', 'base_coin_id')
    op.drop_column('user', 'difference')
    op.drop_column('user', 'on_skew')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('on_skew', postgresql.ENUM('BINANCE', 'BYBIT', name='exchangename'), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('difference', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('base_coin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('test_api', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_base_coin_id_fkey', 'user', 'coin', ['base_coin_id'], ['id'])
    op.drop_column('user', 'executed_bybit')
    op.drop_column('user', 'executed_binance')
    op.drop_column('user', 'init_volume')
    # ### end Alembic commands ###
